[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"

[project]
name = "pcrglobwb2"
version = "0.2.0"
description = "Python 3 port of PCR-GLOBWB + BMI"
authors = [
    { name = "A.B. van der Veen" }
]
dependencies = [
    "cython",
    "pydantic",
    "bmipy",
    "numpy",
    "xarray",
    "netcdf4",
]

[tool.hatch.build]
packages = ["model"]

